---
    version: "3.8"
    
    services:
      client:
        image: node:18.0.0-alpine
        user: node
        entrypoint: sh -c
        working_dir: /home/node
        command: '"npm install && npm run dev"'
        ports:
          - 5173:5173
        volumes:
          - ./front:/home/node
    
      server:
        image: node:18.0.0-alpine
        user: node
        tty: true
        stdin_open: true
        working_dir: /home/node
        entrypoint: sh -c
        command: '"npm install && npm run start"'
        ports:
          - 8000:8000
        volumes:
          - ./back:/home/node
    