---
    version: "3.8"
    
    services:
      client:
        image: node:20.0.0-alpine
        user: node
        entrypoint: sh -c
        working_dir: /home/node
        command: '"npm install && npm run dev"'
        ports:
          - 5173:5173
        volumes:
          - ./front:/home/node
    
      server:
        image: node:20.0.0-alpine
        user: node
        tty: true
        stdin_open: true
        working_dir: /home/node
        entrypoint: sh -c
        command: '"npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"'
        ports:
          - 8000:8000
        volumes:
          - ./back:/home/node
        environment:
          - DATABASE_URL=postgresql://postgres:gouenjistar123@db:5432/ecommerce
          - PORT=8000
          - JWT_SECRET=Welcome1ufzojt3T2UvalhgVqDy
          - SMTP_HOST=maildev
          - SMTP_PORT=1025
        depends_on:
          - db
          
      db:
        image: postgres:14
        environment:
          - POSTGRES_DB=ecommerce
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=gouenjistar123
        volumes:
          - postgres-data:/var/lib/postgresql/data
        ports:
          - 5432:5432

      pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@example.com
          - PGADMIN_DEFAULT_PASSWORD=admin_password
        ports:
          - 16543:80
        volumes:
          - pgadmin-data:/var/lib/pgadmin
        depends_on:
          - db
          
      maildev:
        image: maildev/maildev
        command: bin/maildev --web 1080 --smtp 1025
        ports:
          - 1080:1080
          - 1025:1025
        
    volumes:
      postgres-data:
      pgadmin-data:
    